config/routes.rb
SpaceComby::Application.routes.draw do

  resources :reviews

  get "land_page/landingpage"
  resources :orders do
  get 'express', :on => :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


  get "places/:id/review" => 'places#review'
  get "places/:id/rating" => 'places#rating'
  get "account/index"
  get "users/settings"
  get "places/index"
  get "places/verify"
  get "places/number"
  get "display/index"
  get "places/done"
  resources :orders
  resources :line_items
  resources :carts
  resources :ratings
  resources :places
  resources :store
  resources :devise
  resources :users
  get 'lease/index'
  get 'booking/index'
  get 'show/:id' => 'user#show'
  match 'contact' =>"contact#new", as: 'contact', via: [:get]
  match 'contact' =>"contact#create", via: [:post]

  get "about/tos" => "about#tos", as: 'tos'
  get "about/privacy" => "about#privacy", as: 'privacy'
  get "about/team" => "about#team", as: 'team'
  get "about/hostwithus" => "about#hostwithus", as: 'hostwithus'
  get "about/howitworks" => "about#howitworks", as: 'howitworks'
  get "about/analytics" => "about#analytics", as: 'analytics'
    get "about/static" => 'about#static', as: 'static'

  get "welcome/index"
  get "users/registrations/new" =>'users#new', as: 'new' 
  get "welcome/payment" =>'welcome#payment', as: 'payment'
  get "welcome/profile" =>'welcome#profile', as: 'profile'
  root 'welcome#index'

  get "welcome/aboutus" => 'welcome#aboutus', as: 'aboutus'
  get "welcome/dashboard" => 'welcome#dashboard', as: 'dashboard'
  get "welcome/stays" => 'welcome#stays', as: 'stays'
  get "account/index" => 'account#index', as: 'index'
  get "welcome/content" => 'welcome#content', as: 'content'


   
  get "*path"=>redirect("/")
    







  

end

app/models/order_place.rb
class OrderPlace < ActiveRecord::Base
	belongs_to :order
	belongs_to :place
end

app/controllers/order_places_controller.rb
class OrderPlacesController < ApplicationController
  before_action :set_order_place, only: [:show, :edit, :update, :destroy]

  # GET /order_places
  # GET /order_places.json
  def index
    @order_places = OrderPlace.all
  end

  # GET /order_places/1
  # GET /order_places/1.json
  def show
  end

  # GET /order_places/new
  def new
    @order_place = OrderPlace.new
  end

  # GET /order_places/1/edit
  def edit
  end

  # POST /order_places
  # POST /order_places.json
  def create
    @order_place = OrderPlace.new(order_place_params)

    respond_to do |format|
      if @order_place.save
        format.html { redirect_to @order_place, notice: 'Order place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order_place }
      else
        format.html { render action: 'new' }
        format.json { render json: @order_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_places/1
  # PATCH/PUT /order_places/1.json
  def update
    respond_to do |format|
      if @order_place.update(order_place_params)
        format.html { redirect_to @order_place, notice: 'Order place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_places/1
  # DELETE /order_places/1.json
  def destroy
    @order_place.destroy
    respond_to do |format|
      format.html { redirect_to order_places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_place
      @order_place = OrderPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_place_params
      params.require(:order_place).permit(:order_id, :place_id)
    end
end

app/helpers/order_places_helper.rb
module OrderPlacesHelper
end

app/views/order_places/_form.html.erb
<%= form_for(@order_place) do |f| %>
  <% if @order_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_place.errors.count, "error") %> prohibited this order_place from being saved:</h2>

      <ul>
      <% @order_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.number_field :place_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_places/edit.html.erb
<h1>Editing order_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_place %> |
<%= link_to 'Back', order_places_path %>

app/views/order_places/index.html.erb
<h1>Listing order_places</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_places.each do |order_place| %>
      <tr>
        <td><%= order_place.order_id %></td>
        <td><%= order_place.place_id %></td>
        <td><%= link_to 'Show', order_place %></td>
        <td><%= link_to 'Edit', edit_order_place_path(order_place) %></td>
        <td><%= link_to 'Destroy', order_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order place', new_order_place_path %>

app/views/order_places/new.html.erb
<h1>New order_place</h1>

<%= render 'form' %>

<%= link_to 'Back', order_places_path %>

app/views/order_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_place.order_id %>
</p>

<p>
  <strong>Place:</strong>
  <%= @order_place.place_id %>
</p>

<%= link_to 'Edit', edit_order_place_path(@order_place) %> |
<%= link_to 'Back', order_places_path %>