config/routes.rb
SpaceComby::Application.routes.draw do

  resources :reviews

  get "land_page/landingpage"
  resources :orders do
  get 'express', :on => :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


  get "places/:id/review" => 'places#review'
  get "places/:id/rating" => 'places#rating'
  get "account/index"
  get "users/settings"
  get "places/index"
  get "places/verify"
  get "places/number"
  get "display/index"
  get "places/done"
  resources :orders
  resources :line_items
  resources :carts
  resources :ratings
  resources :places
  resources :store
  resources :devise
  resources :users
  get 'lease/index'
  get 'booking/index'
  get 'show/:id' => 'user#show'
  match 'contact' =>"contact#new", as: 'contact', via: [:get]
  match 'contact' =>"contact#create", via: [:post]

  get "about/tos" => "about#tos", as: 'tos'
  get "about/privacy" => "about#privacy", as: 'privacy'
  get "about/team" => "about#team", as: 'team'
  get "about/hostwithus" => "about#hostwithus", as: 'hostwithus'
  get "about/howitworks" => "about#howitworks", as: 'howitworks'
  get "about/analytics" => "about#analytics", as: 'analytics'
    get "about/static" => 'about#static', as: 'static'

  get "welcome/index"
  get "users/registrations/new" =>'users#new', as: 'new' 
  get "welcome/payment" =>'welcome#payment', as: 'payment'
  get "welcome/profile" =>'welcome#profile', as: 'profile'
  root 'welcome#index'

  get "welcome/aboutus" => 'welcome#aboutus', as: 'aboutus'
  get "welcome/dashboard" => 'welcome#dashboard', as: 'dashboard'
  get "welcome/stays" => 'welcome#stays', as: 'stays'
  get "account/index" => 'account#index', as: 'index'
  get "welcome/content" => 'welcome#content', as: 'content'


   
  get "*path"=>redirect("/")
    







  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
  has_one :order
  belongs_to :user
  

	
  def add_place(place_id)
    current_item = line_items.find_by_place_id(place_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:place_id => place_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_amount }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
layout "application2"
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    if user_signed_in?

    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
    end
  else
    redirect_to user_session_path
end
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create

    @user = current_user

    @cart.user_id = current_user.id

    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
 def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(places_path,
        :notice => 'Your cart is currently empty') }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

     

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
 <% provide(:title, 'My Cart') %>

<% if @cart.line_items.empty?%>

<div class="row">
    <div class="content-wrapper twelve columns">
<h1 style="margin-left:20px;">My Cart</h1>
      <div class="row">
        <div class="three columns" style="width:74%">
          <div style="margin-left:15px;">
        <br/><br/>
         Your cart is currently empty.
 <br/><br/>
              <a href="/places/index" class="btn btn_gray"><i class="icon-chevron-left" ></i>&nbsp;Continue Booking</a>
         </div>
         </div>
              <div class="three columns">
        <div class="widget-container widget-text" id="widget-ID-name">
          <h3 class="widgettitle"><i class="icon-lock"></i>&nbsp;&nbsp;&nbsp;Secured Payment</h3>
          <div class="widget-content">
            <div class="contact-text">
              <ul>
                <li>

                  <span>
                   This website is secured. Your personal details are protected at all times.<br/>
                   <div align="center">

                    <%= image_tag "../assets/images/verify.gif " ,:style=>"width:210px;" %></a><br/>
                    <%= image_tag "../assets/images/verisign.jpg" ,:style=>"width:150px;" %></a>

                  </div>
                </span>
                <div class="clear"></div>
              </li>

            </ul>
          </div>
        </div>
      </div>
      <br/>
      <div class="widget-container widget-text" id="widget-ID-name">
        <h3 class="widgettitle">Need Help?</h3>
        <div class="widget-content">
          <div class="contact-text">
            <ul>
              <li>

                <span>If you encounter any issues, please contact us at:</span><br/><BR/><br/>
                <b>General Enquiries:</b><BR/>info@spacecomby.com<br/><br/>
                <b>Sales Enquiries:</b><BR/>sales@spacecomby.com<br/>
                <div class="clear"></div>
              </li>


            </ul>
          </div>
        </div>
      </div>

    </div>


  </div>
         </div>

         </div>

         </div>


<%else%>
<div class="page-wrapper twelve columns no-sidebar b0">
  <div class="row">
    <div class="twelve columns b0">
      <div class="page-title-wrapper" style="margin-left:-10px;">
        <h1 class="page-title left" >
          Your Cart</h1>
          <div class="page-title-alt right">
          </div>
          <div class="clear">
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="row">
    <div class="content-wrapper twelve columns">

      <div class="row">
        <div class="three columns" style="width:74%">
          <div style="margin-left:15px;">
           <a href="/places/index" class="btn btn_gray"><i class="icon-chevron-left" ></i>&nbsp;Continue Booking</a><br/><br/>
         </div>
         <div class="cpt-items row clearfix isotope" style=" margin-left:20px;">
           <% if user_signed_in? %>                             
           <% @cart.line_items.each do |item| %>  
           <div class="cpt-item five columns isotope-item rooms">
            <div class="thumb-wrapper">
              <% if item.place.image? %>
              <%= image_tag(item.place.image.url) %>

              <% else %>
              <%= image_tag("../assets/images/missing.jpg", :style=>"width:280px;height:160px;") %>
              <% end %>
              <div class="thumb-control-wrapper">
                <ul class="thumb-control clearfix">
                  <li style="margin-left:20px;"><a title="View Detail" href="/places/<%=item.place.id%>" class="go-detail">Open Detail</a></li>
                
                </ul>
              </div>
            </div>

          </div> 
          <A href="/places/<%=item.place.id%>"><span class="recent-date" style="font-size:20px ;color:black;"><b><%= item.place.title %></b></span></a>
            <br/>
            <BR/>
            <BR/>
            <span class="recent-date" style="color:#808080;font-size:14px;"><i class="icon-briefcase" ></i>&nbsp; TYPE<h style ="margin-left:92px;text-transform:uppercase;"><%= item.place.wsType %></h></span>


            <br/>
            <span class="recent-date"style="color:#808080;font-size:14px;"><i class="icon-calendar"></i>&nbsp;&nbsp;CHECK IN  <h style ="margin-left:60px;"><%= item.place.select_start %></h></span>
            <br/>
            <span class="recent-date"style="color:#808080;font-size:14px;"><i class="icon-calendar"></i>&nbsp;&nbsp;CHECK OUT <h style ="margin-left:44px;"><%= item.place.select_end %></h></span> 
            <br/> <br/>
            <span class="recent-date"style="color:#808080;font-size:16px ;margin-left:230px;"><i class="icon-check"></i>&nbsp;&nbsp;Price:&nbsp;&nbsp; <h><%= number_to_currency(item.total_price) %>/day</h></span>
          </div>  



          <div style=" margin-left:20px;">



            <HR/>
            <% end %>    


          
            <div align="right">
             
           <i class="icon-money"></i> Grand Total: &nbsp;&nbsp;<%= number_to_currency(@cart.total_price) %>
            </div>
<div   style="margin-top:-20px; ">
            <%= button_to 'Remove all bookings', @cart, :method => :delete, :confirm => 'Are you sure?', :class=>"btn btn-primary higher bold" %> 
</div>
            <br/><br/>
            <div align="right"> 
             <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), express_orders_path %>


             &nbsp;&nbsp; &nbsp;&nbsp;<b>OR &nbsp;&nbsp; &nbsp;&nbsp;</b>

             <%= link_to "Pay Now", new_order_path , :class=>"btn btn_orange"%><br/><br/>

             <input type="checkbox" required="required" checked="checked">I agree to the cancellation policy, house rules, guest refund policy terms, and terms of service.</input>

           </div>
         </div>

         <% else %>

         <%= render "place/new" %>

         <% end %>
       </div>
       <div class="three columns">
        <div class="widget-container widget-text" id="widget-ID-name">
          <h3 class="widgettitle"><i class="icon-lock"></i>&nbsp;&nbsp;&nbsp;Secured Payment</h3>
          <div class="widget-content">
            <div class="contact-text">
              <ul>
                <li>

                  <span>
                   This website is secured. Your personal details are protected at all times.<br/>
                   <div align="center">

                    <%= image_tag "../assets/images/verify.gif " ,:style=>"width:210px;" %></a><br/>
                    <%= image_tag "../assets/images/verisign.jpg" ,:style=>"width:150px;" %></a>

                  </div>
                </span>
                <div class="clear"></div>
              </li>

            </ul>
          </div>
        </div>
      </div>
      <br/>
      <div class="widget-container widget-text" id="widget-ID-name">
        <h3 class="widgettitle">Need Help?</h3>
        <div class="widget-content">
          <div class="contact-text">
            <ul>
              <li>

                <span>If you encounter any issues, please contact us at:</span><br/><BR/><br/>
                <b>General Enquiries:</b><BR/>info@spacecomby.com<br/><br/>
                <b>Sales Enquiries:</b><BR/>sales@spacecomby.com<br/>
                <div class="clear"></div>
              </li>


            </ul>
          </div>
        </div>
      </div>

    </div>


  </div>

  <div class="clear"></div>
</div>


</div>
</div>
<%end%>