config/routes.rb
SpaceComby::Application.routes.draw do

  resources :reviews

  get "land_page/landingpage"
  resources :orders do
  get 'express', :on => :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


  get "places/:id/review" => 'places#review'
  get "places/:id/rating" => 'places#rating'
  get "account/index"
  get "users/settings"
  get "places/index"
  get "places/verify"
  get "places/number"
  get "display/index"
  get "places/done"
  resources :orders
  resources :line_items
  resources :carts
  resources :ratings
  resources :places
  resources :store
  resources :devise
  resources :users
  get 'lease/index'
  get 'booking/index'
  get 'show/:id' => 'user#show'
  match 'contact' =>"contact#new", as: 'contact', via: [:get]
  match 'contact' =>"contact#create", via: [:post]

  get "about/tos" => "about#tos", as: 'tos'
  get "about/privacy" => "about#privacy", as: 'privacy'
  get "about/team" => "about#team", as: 'team'
  get "about/hostwithus" => "about#hostwithus", as: 'hostwithus'
  get "about/howitworks" => "about#howitworks", as: 'howitworks'
  get "about/analytics" => "about#analytics", as: 'analytics'
    get "about/static" => 'about#static', as: 'static'

  get "welcome/index"
  get "users/registrations/new" =>'users#new', as: 'new' 
  get "welcome/payment" =>'welcome#payment', as: 'payment'
  get "welcome/profile" =>'welcome#profile', as: 'profile'
  root 'welcome#index'

  get "welcome/aboutus" => 'welcome#aboutus', as: 'aboutus'
  get "welcome/dashboard" => 'welcome#dashboard', as: 'dashboard'
  get "welcome/stays" => 'welcome#stays', as: 'stays'
  get "account/index" => 'account#index', as: 'index'
  get "welcome/content" => 'welcome#content', as: 'content'


   
  get "*path"=>redirect("/")
    







  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :place
	belongs_to :cart
	belongs_to :order

	def total_price 
		place.price * quantity
	end

	def count_days
  (place.select_end - place.select_start).to_i
 end 

 	def total_amount 
 		total_price * count_days
 	end	


 	def final_price
    line_items.to_a.sum { |item| item.total_amount }
  end
  
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @cart = current_cart
    @place = Place.find(params[:place_id])
    if @place.select_start.blank? || @place.select_end.blank?
      flash[:notice] = "Please select the dates before proceeding"
      redirect_to :back
    else 
    @line_item = @cart.add_place(@place.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(@line_item.cart) }
        format.xml  { render :xml => @line_item,
          :status => :created, :location => @line_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @line_item.errors,
          :status => :unprocessable_entity }
      end
    end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(line_items_url) }
      format.xml  { head :ok }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:place_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.number_field :place_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.place_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @line_item.place_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>