config/routes.rb
SpaceComby::Application.routes.draw do

  resources :reviews

  get "land_page/landingpage"
  resources :orders do
  get 'express', :on => :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', confirmations: 'users/confirmations', sessions: 'users/sessions' }, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


  get "places/:id/review" => 'places#review'
  get "places/:id/rating" => 'places#rating'
  get "account/index"
  get "users/settings"
  get "places/index"
  get "places/verify"
  get "places/number"
  get "display/index"
  get "places/done"
  resources :orders
  resources :line_items
  resources :carts
  resources :ratings
  resources :places
  resources :store
  resources :devise
  resources :users
  get 'lease/index'
  get 'booking/index'
  get 'show/:id' => 'user#show'
  match 'contact' =>"contact#new", as: 'contact', via: [:get]
  match 'contact' =>"contact#create", via: [:post]

  get "about/tos" => "about#tos", as: 'tos'
  get "about/privacy" => "about#privacy", as: 'privacy'
  get "about/team" => "about#team", as: 'team'
  get "about/hostwithus" => "about#hostwithus", as: 'hostwithus'
  get "about/howitworks" => "about#howitworks", as: 'howitworks'
  get "about/analytics" => "about#analytics", as: 'analytics'
    get "about/static" => 'about#static', as: 'static'

  get "welcome/index"
  get "users/registrations/new" =>'users#new', as: 'new' 
  get "welcome/payment" =>'welcome#payment', as: 'payment'
  get "welcome/profile" =>'welcome#profile', as: 'profile'
  root 'welcome#index'

  get "welcome/aboutus" => 'welcome#aboutus', as: 'aboutus'
  get "welcome/dashboard" => 'welcome#dashboard', as: 'dashboard'
  get "welcome/stays" => 'welcome#stays', as: 'stays'
  get "account/index" => 'account#index', as: 'index'
  get "welcome/content" => 'welcome#content', as: 'content'


   
  get "*path"=>redirect("/")
    







  

end

app/models/place.rb
class Place < ActiveRecord::Base
  
    geocoded_by :address
    after_validation :geocode, :if => :address_changed?
    has_many :selections
    has_many :facilities, :through => :selections
    belongs_to :user
    has_many :ratings
    has_many :order_places
    has_many :reviews

    accepts_nested_attributes_for :order_places   
   

    #:normal will create a folder name "normal" and have a version of the image with the resolution as preset below. 
    #The original file will be placed in the "original" folder
  has_attached_file :image, :styles => { 
    :normal => "642x335#",
    :tiny => "70x50#",
    :thumbnail => "100x100#",
    :small  => "150x150>",
    :medium => "300x300>" }, 
    :default_style => :normal

  searchable do 
    text :title, :description, :address, :country, :wsType
    integer :maxOccupancy
    string :wsType
  end
  
 

 include ActiveModel::Validations
 

  validates :title, :presence => true
  validates :description, :presence => true
  validates :maxOccupancy, :presence => true, :numericality => true
  validates :wsType, :presence => true
  validates :telNumber, :presence => true, :numericality =>true
  validates :startTime, :presence => true
  validates :endTime, :presence => true
  validates :price, :presence => true, :numericality =>true, :inclusion => { :in => 1..10000000 }
 
    
  

  def average_rating
    @value = 0
    self.ratings.each do |rating|
        @value = @value + rating.value
    end
    @total = self.ratings.size
    @value.to_f / @total.to_f
end



  private

  #For slider-range
  scope :filter, lambda { |low, high| { :conditions => { :price => low..high } } }

  def self.high_low_prices
    [Place.minimum(:price), Place.maximum(:price)]
  end
  #End slider-range



end

app/controllers/places_controller.rb
 class PlacesController < ApplicationController
    layout 'application2'
    before_action :set_place, only: [:show, :edit, :update, :destroy]
    helper_method :redirect_to

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
   
    @search = Place.search do
      fulltext params[:search]
    end
    @places = @search.results
    
    #For slider-range
      unless params[:low] && params[:high]
        @place = Place.all
      else
        @place = Place.filter(params[:low], params[:high])
      end  
        @price_range = Place.high_low_prices
      #End slider-range
  end

  # GET /places/1
  # GET /places/1.json
  def show
   render :layout => 'application'
   @place = Place.find(params[:id])
   #@user = User.find(:all, :conditions => {:id => current_user.id})
  end

  # GET /places/new
  def new
    if user_signed_in?
      @user = current_user
      if(@user.phone_number.blank?)
        render :action => "number"

    elsif(@user.sms_confirmed? == false)
        # fires off a TXT to the user with a generated confirmation code
        @user.send_sms_confirmation!
        render :action => "verify"
      else
        @place = Place.new
      end
    else
        redirect_to user_session_path
    end
  end


  def number
    @user = current_user
    render :action => "verify"
end

  # GET /places/1/edit
  def edit
    @user = current_user
    @place = Place.find(params[:id])
    unless @user.id == @place.user_id && user_signed_in?
    flash[:notice] = "You do not have the access to edit"
    redirect_to place_path
    end 
  end

  #For rating
  def rating
   @place = Place.find(params[:id])
  end

  def review
    @place = Place.find(params[:id])
   end 

  #For sms verification
  def verify
    @user = current_user 
    @user.sms_confirm_with(params[:verify_code])
    if(@user.sms_confirmed? == true)
      @place = Place.new
      render :action => "new"
      else
        flash.now[:error] = "Wrong code"
        render action: "verify"
      end
  end

    # POST /places
    # POST /places.json
    def create
      @place = Place.new(place_params)
      @place.save
      @user = current_user
      @place.user_id = current_user.id

      respond_to do |format|
        if @place.save
          format.html { redirect_to @place, notice: 'Place was successfully created.' }
          format.json { render action: 'show', status: :created, location: @place }
        else
          format.html { render action: 'new' }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    end


  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    params[:place][:facility_ids] ||= []
    @place = Place.find(params[:id])
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to :back , notice: 'Your listing has been successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
        params.require(:place).permit(:title, :description, :address, :latitude, :longitude, :maxOccupancy, :wsType, :telNumber, :startTime, :endTime, :price, :rating, :review, :image, :image_file_name, :image_content_type, :image_file_size, :image_updated_at, :start_date, :end_date, :select_start, :country, :postal, :select_end, :facility_ids => [])
    end
    
  end

def static
 
end

app/helpers/places_helper.rb
module PlacesHelper
	def rating_ballot
    if @rating = current_user.ratings.find_by_place_id(params[:id])
        @rating
    else
        current_user.ratings.new
    end
end


def review_ballot
    if @review = current_user.reviews.find_by_place_id(params[:id])
        @review

    else
        current_user.reviews.new
    end
end

def current_user_rating
    if @rating = current_user.ratings.find_by_place_id(params[:id])
        @rating.value
    else
        "N/A"
    end
end


end

app/views/places/_done.html.erb
YOU CANT REVIEW ANYMORE, YOUR REVIEW HAS ALREADY BEEN SUBMITTED!

app/views/places/done.html.erb
YOU CANT REVIEW ANYMORE, YOUR REVIEW HAS ALREADY BEEN SUBMITTED!

app/views/places/edit.html.erb
<head>
</head>

<% provide(:title, 'Edit_Your_Workspace') %>



<div class="main-wrapper container">
 <div class="row row-wrapper">
 <div class="page-outer-wrapper">
 <div class="page-wrapper twelve columns no-sidebar b0">


     <div class="row">
        <div class="twelve columns b0">
          <div class="page-title-wrapper">
                <h1 class="page-title left">Edit Your Workspace</h1>
                <div class="page-title-alt right"></div>
                <div class="clear"></div>
       		</div>
        </div>
     </div>

<div class="row">

<%= render 'form' %>


<div class="sidebar right-sidebar-wrapper four columns">
                                    


    
                                </div>
                                 <div class="clear"></div>

</div> <!--end .row -->


</div>
 <div class="clear"></div>
</div>
</div>
</div>

app/views/places/index.html.erb
 <% provide(:title, 'Listings') %>

  <style>
    .cpt-detail{
      color:#bca474!important;
    }
  </style>

  <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

  <script>
  $(function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  });
  </script>
  
 <script>
  function showPlaces(minPrice, maxPrice) {
    $("#spaces #lol").hide().filter(function() {
//$("#list_line_odd").hide().filter(function() {
  var price = parseFloat($(this).data("price"), 10.0);
  return price >= minPrice && price <= maxPrice;
}).show();
  }
  jQuery(document).ready(function ($) {
    min = <%= @price_range.first %>;
    max = <%= @price_range.last %>;
    var options = {
      range: true,
      min: <%= @price_range.first %>,
      max: <%= @price_range.last %>,
      values: [min, max],
      slide: function(event, ui) {
        var min = ui.values[0],
        max = ui.values[1];

        $("#amount").val("$" + min + " - $" + max);
        showPlaces(min, max);
      }
    }, min, max;

    $("#slider-range").slider(options);
    $("#amount").val("$" + min + " - $" + max);
    showPlaces(min, max);
  });
  </script>

  <style>
   .info {  position: relative;padding: 10px 35px 10px 14px;margin: 20px 0;background-color: #b9dbee;color: #3a87ad;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px; width:87%;
  }




</style>


  <div class="main-wrapper container">
    <div class="row row-wrapper">
      <div class="page-outer-wrapper">
        <div class="page-wrapper twelve columns no-sidebar b0">
          
           <div id="sb-search" class="sb-search">
                <form>
                <%= form_tag places_index_path, :method => :get do %>

                   <%= text_field_tag :search, params[:search],:class=>'sb-search-input', :placeholder=>'Enter your search term...',:type=>'text',:name=>'search', :id=>'search', :for=>'tags' %>
                   <input id="tags">
                   <%= submit_tag "", :class => 'sb-search-submit', :type=>'submit', :name=>'nil'%>
                  <span class="sb-icon-search"></span>
                    <% end %>
                </form>
              </div>
        
          <div class="row">
            <div class="twelve columns b0">
              <div class="builder-item-wrapper builder-portfolio">

                <div class="builder-title-wrapper clearfix has_filter">
                  <h3 class="builder-item-title"></h3>
                  <div class="builter-title-alt right">

                  </div>
                  <div class="clear"></div>
                </div>

                <div class="builder-item-content row">


                 <div class="twelve columns b0" style="float:right;width:100%;padding-bottom:3em;">



                  <table style="width:90%;margin: 0 auto; height:100%;">

                    <tr style="border-bottom:1px solid #ccc;">
                      <td style="width:30%;">
                        <p style="font-family: 'Roboto',Arial,sans-serif;color:black;margin:20px auto;">WORKSPACE TYPE</p>
                      </td>

                      <td style="width:100%;">
                        <div class="builter-title-alt right" style="margin:20px auto;">
                          <ul class="cpt-filters">
                           <li> <%= link_to "All", :controller => "places" ,:search => "" %></li>
                            <li> <%= link_to "Co-Working Space", :controller => "places" ,:search => "co-working" %></li>
                            <li> <%= link_to "Meeting Room", :controller => "places" ,:search => "meeting" %></li>
                            <li> <%= link_to "Startup Incubator", :controller => "places" ,:search => "startup" %></li>
                          </ul>


                        </div><!--builter-title-alt right-->
                      </td>
                    </tr>

                    <tr style="border-bottom:1px solid #ccc;">
                      <td style="width:30%;">
                        <div style="margin:20px auto;">
                          <label for="amount" style="font-family: 'Roboto',Arial,sans-serif;color:black;">PRICE RANGE:</label>
                          <input type="text" id="amount" style="border:0;background-color:White; color:#f6931f;width:10em;;font-weight:bold;" />
                        </div>
                      </td>

                      <td style="width:100%;">
                      <div id="slider-range" style="width:100%;margin:20px auto;"></div >  
                        </td>
                      </tr>
                    </table>   
                    <br/>
                    <br/>


                  </div>  


                  <div class="twelve columns b0">
                    <div class="cpt-items row clearfix isotope">

                        <div class="places">
<% if @places.empty? %>
<div class="info" style="margin-top:-50px;margin-left:64px;">Your search returns no results.</div>
<%else%>
                     <% @places.each do |place| %>
               
                     <div id="spaces">
                      <div name="lol" id="lol" class="<%= cycle('list_line_odd', 'list_line_even') %>" data-price="<%= place.price %>">
                        <div class="cpt-item four columns isotope-item logo">
                          <div class="thumb-wrapper">
                            <% if place.image? %>
                            <%= image_tag place.image.url(:normal) %>
                            <% else %>
                            <%= image_tag("../assets/images/missing.jpg", :style=>"width:500px;height:155px;") %>
                            <% end %>

                            <div class="thumb-control-wrapper">
                              <ul class="thumb-control clearfix">
                             <li style="margin-left:20px;"><a title="View Detail" href="/places/<%=place.id%>" class="go-detail">Open Detail</a></li>


                               
                              </ul>
                            </div>
                          </div>
                          <div class="cpt-detail" style="text-align:center;">
                            <h2 class="cpt-title"><a href=""><%= link_to place.title, place %></a></h2>
                            <div class="cpt-desc">S<%= number_to_currency(place.price) %></div>
                          </div>
                        </div>

                      </div>
                   </div>
                    <% end %>
                  <% end %>
                        </div>
                  </div>
                </div>
              </div>

              <div class="clear"></div>
            </div> <!-- END .row -->

          </div> <!-- END .page-wrapper -->
          <div class="clear"></div>

        </div> <!-- END .page-outer-wrapper -->
      </div>
    </div> <!-- END .main-wrapper -->

  </div>
</div>

<script>
  new UISearch( document.getElementById( 'sb-search' ) );
  </script>

      

app/views/places/list.html.erb


<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Maxoccupancy:</strong>
  <%= @place.maxOccupancy %>
</p>

<p>
  <strong>Wstype:</strong>
  <%= @place.wsType %>
</p>

<p>
  <strong>Telnumber:</strong>
  <%= @place.telNumber %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @place.start_date %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @place.end_date %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @place.startTime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @place.endTime %>
</p>

<p>
  <strong>Price:</strong>
  <%= @place.price %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @place.rating %>
</p>

<% if @place.image? %>
  <%= image_tag @place.image.url(:normal) %>
  <br />
<% end %>

<p>
<strong> Facilities: </strong>
<% @place.facilities.each do |facility| %>
<li><%= facility.name%>
</li><% end %>
</p>

  <%= @place.user.email %>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/places/new.html.erb
<head>
</head>

<% provide(:title, 'List Your Workspace') %>

<div class="main-wrapper container">
 <div class="row row-wrapper">
 
 <div class="page-outer-wrapper">
 <div class="page-wrapper twelve columns no-sidebar b0">


     <div class="row">
        <div class="twelve columns b0">
          <div class="page-title-wrapper">
                <h1 class="page-title left">List Your Workspace</h1>
                <div class="page-title-alt right"></div>
                <div class="clear"></div>
            </div>
        </div>
     </div>

<%= render 'form' %>

<div class="clear"></div>

</div>
 <div class="clear"></div>
</div>
</div>
</div>

app/views/places/number.html.erb
   <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }, :multipart => true) do |f| %> 
													<!-- <label for="verification code">Verification</label> -->
												



 
<style type="text/css">

	/*Search Button*/
	
	.verifyMain
	{
		-moz-border-radius:4px !important;
		-webkit-border-radius:4px!important;
		border-radius:4px!important;
		-webkit-box-shadow: 0 0 5px 1px rgba(0, 0, 0, 0.2);
		border:1px solid #ccc;
	}

	.VerifyTable{

width:600;
 border:0; 
 align:center;
 cellpadding:0;
 cellspacing:0;
 
border-top:#ff580e solid 5px !important;
-moz-border-radius:4px !important; 
-webkit-border-radius:4px !important; 
border-radius:4px!important;
}


@media only screen and (max-width:640px)

{
    
    .main{width: 440px !important;}
    .inner{width: 400px !important;}
    .column{width: 440px !important;}
    
}

@media only screen and (max-width:479px)

{
    .main{width: 280px !important;}
    .inner{width: 240px !important;}
    .column{width: 240px !important;}
}

    #number:focus{
      outline:0;
      border-radius:3px!important;
      border:1px solid #ff6a2f!important;
      /* border-color: #f64300;*/
      box-shadow: 0 0 7px #ff6a2f;
    }
</style>

	<div>

		<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="main-bg" style="background:#eeeeee;">
			
			<tr>
				<td align="center" valign="top" style="padding-bottom:60px;">

				
					<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" class="main">

						<br /><br />
						<tr>
							<td align="left" valign="top">

								
								<table class="VerifyTable">

									<tr>
										<td class ="verifyMain" align="left" valign="top" bgcolor="#fff" style="background:#fff; padding-top:19px; padding-bottom:22px;"><table width="570" border="0" align="center" 
											cellpadding="0" cellspacing="0" class="inner">
											
											<tr>
												<td align="center" valign="top" style="font-size: 20px; color:#525252; padding-top:2px;">
													<b>Please key in your mobile number before proceeding</b>

												</td>
											</tr>
											
											<tr>
												<td align="center" valign="top" style="padding-bottom:1em;">

	<label>Enter your phone number below</label><br>
                    <%= f.text_field :phone_number,:style=>"width: 60%; border-radius:3px;color:black; border:1.5px solid #ccc; background:#ffffff;font-size: 12px;", :class=>"number ", :id=>"number"%>
                  <br/><br/>
													<%= submit_tag "Submit" , :class=>"btn btn_orange"%>

												


												</td>
											</tr>
										</table></td>
									</tr>

								</table>
								

							</td>
						</tr>
					</table>    
				
				</td>
			</tr>
		
			</table>

		</div>


														<% end%>

app/views/places/rating.html.erb
<style>
/*sprite with stars*/
#reviewStars-input input:checked ~ label, #reviewStars-input label, #reviewStars-input label:hover, #reviewStars-input label:hover ~ label {
  background: url('http://positivecrash.com/wp-content/uploads/ico-s71a7fdede6.png') no-repeat;
}

#reviewStars-input {
  
  /*fix floating problems*/
  overflow: hidden;
  *zoom: 1;
  /*end of fix floating problems*/
  
  float:left;
  margin-left:125px;

}

#reviewStars-input input {
  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=0);
  opacity: 0;
  
  width: 43px;
  height: 40px;
  
  position: absolute;
  top: 0;
  z-index: 0;
}

form.rating_ballot label.rating.bright {
  background-position: 0 -40px;
  height: 40px;
  width: 43px;
}

form.rating_ballot label.rating {
  background-position: 0 0;
  height: 40px;
  width: 43px;
  float: right;
  cursor: pointer;
  margin-right: 10px;
  
  position: relative;
  z-index: 1;
}

#reviewStars-input label:hover, #reviewStars-input label:hover ~ label {
  background-position: 0 -40px;
  height: 40px;
  width: 43px;
}

#reviewStars-input #star-0 {
  left: 0px;
}
#reviewStars-input #star-1 {
  left: 53px;
}
#reviewStars-input #star-2 {
  left: 106px;
}
#reviewStars-input #star-3 {
  left: 159px;
}
#reviewStars-input #star-4 {
  left: 212px;
}
#reviewStars-input #star-5 {
  left: 265px;
}

/*Search Button*/
  
  .ratingMain
  {
    -moz-border-radius:4px !important;
    -webkit-border-radius:4px!important;
    border-radius:4px!important;
    -webkit-box-shadow: 0 0 5px 1px rgba(0, 0, 0, 0.2);
    border:1px solid #ccc;
  }

  .RatingTable{

width:600;
 border:0; 
 align:center;
 cellpadding:0;
 cellspacing:0;
 
border-top:#ff580e solid 5px !important;
-moz-border-radius:4px !important; 
-webkit-border-radius:4px !important; 
border-radius:4px!important;
}


@media only screen and (max-width:640px)

{
    
    .main{width: 440px !important;}
    .inner{width: 400px !important;}
    .column{width: 440px !important;}
    
}

@media only screen and (max-width:479px)

{
    .main{width: 280px !important;}
    .inner{width: 240px !important;}
    .column{width: 240px !important;}
}

</style>


  <style>
  #HomeLogIn {
   margin-top:2.1em;
   margin-right:2em;
    background-color:#ff6a2f;
    padding: 7px 13px 7px 13px;
    padding-bottom: -4px;
    border:2px solid #ff6a2f!important;
     -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    text-align: left;
    
}
#HomeLogIn:hover {
     background:#f05d23; 
     
    
}

#HomeSignUp {
     margin-top:2.1em;
 
    opacity:0.7;
    padding: 7px 13px 7px 13px;
    padding-bottom: -4px;
    border:2px solid #191919!important;
     -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    text-align: left;
    
}

#HomeSignUp:hover {
     border-color:#151411; 
     opacity:0.6;
    
}

  </style>

<div>

    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="main-bg" style="background:#fbf4e4;">
      
      <tr>
        <td align="center" valign="top" style="padding-bottom:60px;">

        
          <table width="600" border="0" align="center" cellpadding="0" cellspacing="0" class="main">

            <br /><br />
            <tr>
              <td align="left" valign="top">

                
                <table class="RatingTable">

                  <tr>
                    <td class ="ratingMain" align="left" valign="top" bgcolor="#fff" style="background:#fff; padding-top:19px; padding-bottom:22px;"><table width="560" border="0" align="center" 
                      cellpadding="0" cellspacing="0" class="inner">
                      
                      <tr>
                        <td align="center" valign="top" style="font:Bold 24px Arial, Helvetica, sans-serif; color:#525252; padding-top:2px;">
                          Rate SpaceComby 
                          <hr>

                          

                        </td>
                      </tr>
                      <tr>
                        <td align="center" valign="top" style="font:Normal 12px Arial, Helvetica, sans-serif; color:#686868; line-height:24px; padding:15px 0px 20px 0px;">
                              How do you like SpaceComby?

                        </td>
                      </tr>
                      <tr>
                        <td align="center" valign="top" style="padding-bottom:1em;">

                        <%= form_for(rating_ballot, :html => { :class => 'rating_ballot' }) do |f| %>
                        <div id="reviewStars-input"> 
                        <%= f.label("value_5", content_tag(:span, ''), {:class=>"rating", :id=>"5"}) %>
                        <%= radio_button_tag("rating[value]", 5, current_user_rating == 5, :class => 'rating_button',:onclick => "this.form.submit();" ) %>
                        <%= f.label("value_4", content_tag(:span, ''), {:class=>"rating", :id=>"4"}) %>
                        <%= radio_button_tag("rating[value]", 4, current_user_rating == 4, :class => 'rating_button',:onclick => "this.form.submit();") %>
                        <%= f.label("value_3", content_tag(:span, ''), {:class=>"rating", :id=>"3"}) %>
                        <%= radio_button_tag("rating[value]", 3, current_user_rating == 3, :class => 'rating_button',:onclick => "this.form.submit();") %>
                        <%= f.label("value_2", content_tag(:span, ''), {:class=>"rating", :id=>"2"}) %>
                        <%= radio_button_tag("rating[value]", 2, current_user_rating == 2, :class => 'rating_button',:onclick => "this.form.submit();") %>
                        <%= f.label("value_1", content_tag(:span, ''), {:class=>"rating", :id=>"1"}) %>
                        <%= radio_button_tag("rating[value]", 1, current_user_rating == 1, :class => 'rating_button',:onclick => "this.form.submit();") %>

                        <%= hidden_field_tag("place_id", @place.id) %>

                             </div>  
                           
                        <% end %>



                        </td>
                      </tr>
                    </table></td>
                  </tr>

                </table>
                

              </td>
            </tr>
          </table>    
        
        </td>
      </tr>
      <tr>
        
        </tr>
      </table>

    </div>